### ISSUE TITLE
Spec whether/when draw events are created for offscreen content

### ISSUE THREAD

**Issue by natduca** [WICG/frame-timing#18]
Spec should consider the following cases or delegate to a csswg spec for:
- display:none
- was it visibility:hidden?
- did it get layout space? eg width*height >0
- is it onscreen
- is it opacity>0?
- was it visible to the user AFTER compositor-changeable properties were applied? Eg, page is janked for 1s: an iframe could have become visible to a user in that time all without js hearing about it.
- was it on the outer viewport but not the inner viewport? Eg its position:fixed but small enough to be hidden by the top controls or the on-screen-keyboard.

**Comment by natduca** [comment]
Also occlusion: if you have an iframe but then put another iframe on top of it that is opaque. Does it get a drawn record?

**Comment by vmpstr** [comment]
I think this is important to make explicit.

Personally, I think that we should only care about visible on-screen content (ie things that you can actually see). The reasons being is here are
1. We don't draw off screen content, so we shouldn't generate composite events.
2. We don't really require or guarantee any work done offscreen for render events.

That being said, if an element is added offscreen that causes layout to run, we might lose this information if the iframe is offscreen. 

Wdyt? I think we gotta agree on this for v1, since the decision will most likely impact the approach we take when implementing.

**Comment by igrigorik** [comment]
@natduca @tabatkins is there any existing csswg language that covers any of these cases? If possible, I'd love to defer this to those specs.

**Comment by mithro** [comment]
When thinking about the `top level` object,
- The "work" should include everything needed to be done to render that image onto the screen. If some of this work involves offscreen content (for example doing layout), then that is perfectly okay. 
- If the `top level` object isn't rendering and image to screen, then it shouldn't be generating events.
- We have already decided to ignore prepainting - is there any other case we do rendering work when not visible?

If you are talking about the case of a page containing iframes, I think what we need to do here depends on the decision in https://github.com/w3c/frame-timing/issues/21

**Comment by igrigorik** [comment]
I believe this no longer relevant due to new slow-only model (see #48). Closing, but feel free to reopen if otherwise.
