### ISSUE TITLE
Add idleTime or "work" variable

### ISSUE THREAD

**Issue by vmpstr** [WICG/frame-timing#31]
From #28, cost = sum of work on all threads. However, we want some way of estimating how much time there is left in a frame, regardless of threads. That is, (paraphrased from @mithro):

idleTime = time during which _no_ thread is doing any work and is not blocked.
work = duration - idleTime

I'm not sure about "work" as the name, but generally I think that's what we're leaning towards?

@mpb, @igrigorik, @mithro, wdyt?

**Comment by mpb** [comment]
I think idleTime is a little easier to explain. workingTime might also be
an option. I think "work" on its own is too confusingly similar to "cost".

**Comment by vmpstr** [comment]
I agree about work vs cost confusion.

I actually really like workingTime. It has "time" in it which kind of implies how long (wall-clock) we're doing work on _any_ of the threads. This is compared to cost, which just happens to be expressed in ms, but it isn't a "time" in a sense. I don't know if that makes sense, or I just made matters more confusing, but overall +1.

**Comment by mithro** [comment]
As mentioned in a chat with @vmpstr. I have no strong preference between `idleTime` verse `workingTime` versions because with the current definition one can be used to calculate the other.

I think `idleTime` is a bit clearer from intuitive understanding of the variable, intuitively your idle when nothing is doing work. `workingTime` is a bit harder to intuitively understand in the multithread context.

As long as you keep the property that you can calculate either, I'm happy for you guys to figure the exact naming without any more input from me.

**Comment by mpb** [comment]
Consolidating into #27
