### ISSUE TITLE
Should Frame Timing report slow frames only?

### ISSUE THREAD

**Issue by igrigorik** [WICG/frame-timing#47]
The goal of FT is to help developers identify jank (<60FPS), as experienced by real-world users running the application on their local hardware. 

As of today, the proposed solution addresses this by surfacing paint + composite events for **every frame**, regardless of how long it took. In turn, as a developer, if I'm interested in detecting jank I'd end up having to subscribe to the full event stream and write a filter to identify slow frames. 

Instead, should we consider surfacing only the slow (>16ms) frames? This still addresses the key use case of Frame Timing and offers some nice advantages. In no particular order...
- The developer does not have to roll their own filter to identify slow records (our primary use case).
- We significantly reduce the amount of emitted records: less overhead for the UA, and less records for the application code to deal with.
- We significantly reduce the potential security+privacy implications of interaction with :visited (https://github.com/w3c/frame-timing/issues/40)
  - By exposing paints for each and every frame, regardless of how long each took, we provide an explicit signal on any "href-triggered repaint" that can be abused to traverse your navigation history. In https://github.com/w3c/frame-timing/issues/40 we discussed a number of plausible mitigations, but none of those were conclusive and would likely come with _high_ implementation complexity and implications.
  - By exposing slow frames only (i.e. >16ms), we significantly reduce the attack surface: FT still emits a record on "href-triggered repaint" whose cost exceeds 16ms, but you can already detect that today  via a rAF timing attack.

That said, we do forfeit some functionality as well. A trivial example is an FPS meter, where you'd want to get records for each and every frame. With slow-only model, you'd end up assuming that lack of FT records means you're running at 60FPS, and then show dips in the meter when you get slow records. That said, perhaps that fine.. we [determined earlier that we won't expose detailed cpu/work timing data](https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0019.html) in FT, so knowing that you had a 'fast record' is not terribly useful on its own.

---

Personally I think the slow-only model offers some nice wins. The :visited interaction alone could be sufficient motivation, and there are additional wins with less UA overhead + developer ergonomics.

Thoughts? Anything that's missing from above analysis? Use-cases, other gotchas?

**Comment by mithro** [comment]
IIRC One of the really import things about the frame-timing API is that it gives you information about _how close you are to falling of the 60fps cliff_. This is really important as it lets you understand if you need to concentrate on optimising things or you can continue to add new features _before_ you trip over the 16ms boundary.

**Comment by igrigorik** [comment]
@mithro that particular use case is not handled by FT today. The current version (report every frame) does not provide any ~cost metrics (see [earlier discussions](https://lists.w3.org/Archives/Public/public-web-perf/2015Jan/0019.html)), and the slow-only version we're exploring here does not change that.

**Comment by eliperelman** [comment]
I think this is a good solution. I couldn't think of any important use cases outside of jank detection and FPS metering that would need fast frames over slow ones, so +1 from me.

**Comment by eliperelman** [comment]
And having a much more compact event stream is a nice side effect. :)

**Comment by toddreifsteck** [comment]
No pushback from me.

**Comment by igrigorik** [comment]
Talked with @mpb, he'll put together a pull to convert to 'slow only'.

**Comment by jdreetz** [comment]
I first became aware of the Frame Timing API as a cross browser alternative to Mozilla's 'mozPaintCount' property - See last comment here: https://code.google.com/p/chromium/issues/detail?id=65348

If the implementation is converted to listing only 'slow' frames, will that prevent something like a 'paint count' from being computed by the Frame Timing API?

Apologies in advance if I'm misunderstanding the scope of the API or the changes being discussed here.

**Comment by igrigorik** [comment]
@jdreetz I don't know the specifics of how mozPaintCount is implemented, but exposing "paint count" runs into the same privacy issues with :visited as discussed in #40. With slow-only model, yes, you wouldn't have access to that (by design). What is your use case that requires exact paint count?

**Comment by jdreetz** [comment]
MozPaintCount is used in the measurement of a video advertising metric called "Viewability":
https://github.com/InteractiveAdvertisingBureau/openvv/blob/master/src/org/openvv/js/OVVAsset.js#L1348

Viewability measurement determines if (and how much of) an ad on a page is visible to the user, for the purpose of preventing fraud. In situations where an ad may not have direct access to the host window/document, usually because it's in a cross domain iframe, several 'beacons' are overlaid on top of the ad and the 'paint count' of each is used as a proxy to determine whether the ad is in view. When the ad is out of view (scrolled for exampled), the paint count/fps drop for the beacons that are no longer in view. 

The method for obtaining the fps of the beacons is typically done using Adobe Flash's fps methods or their 'throttle' event. Not all browsers support this though, so in the case of Firefox, mozPaintCount fulfills this purpose. In the future as Flash is phased out, there will not really be any equivalent methods for measuring this other than mozPaintCount. 

If ad tech developers have the option to use a native component instead of plugins for determining these metrics, it would benefit the web as a whole by preventing more users from having to run these resource heavy components like Flash while still ensuring that fraud is prevented by accurately auditing the sites selling ad spaces.

**Comment by mpb** [comment]
That's one of the primary use cases for Position Observer, https://github.com/slightlyoff/PositionObserver/blob/master/explainer.md
which is a much more targeted API (with less overhead) if all you're trying to get is viewability info.

**Comment by igrigorik** [comment]
@jdreetz thanks for the context! Are you [familiar with Position Observer](https://github.com/slightlyoff/PositionObserver/blob/master/explainer.md) proposal? I think that API is exactly what you're looking for. /cc @slightlyoff

**Comment by jdreetz** [comment]
Thanks for the information @mpb and @igrigorik! Yes, that does sound like a better solution to the problem I've described.

**Comment by hiikezoe** [comment]
I agree that reporting only slow frames reduces the overhead and it's good for users, but
I don't think it mitigate the timing attack.  That is because attackers could easily make slow frames to create while loop in rAF callback.  We should take the approach that @bzbarsky commented[1] to mitigate the timing attack.
[1] https://github.com/w3c/frame-timing/issues/40#issuecomment-101122656

And I wonder web developers want to measure rendering performance on their sites on their development environments?  To catch performance regressions, improve performance, etc.
If a web site takes 15ms in each frames to be rendered constantly, how do they know it? Don't they want to know the site will fall below 60fps in near future?

How about adding a new option like this?

observer.observe({ entryTypes: ['render', 'composite'],  frameTimingThreshold: 16 });

**Comment by igrigorik** [comment]
> I don't think it mitigate the timing attack. That is because attackers could easily make slow frames to create while loop in rAF callback.

I think you're describing a garden variety timing attack against rAF, which is something you can do today without FT. In that sense, you're right that slow-only doesn't "mitigate" timing attacks.. but, I didn't claim that it would. Rather, it leaves you with the same exposure as before. That said, don't get me wrong, I'm not claiming that's a great place to be. We _should_ solve the long-term issue behind :visited, but (a) that's out of scope for FT, and (b) personally I don't think that grafting more and more workaround heuristics is addressing the underlying issue.

> If a web site takes 15ms in each frames to be rendered constantly, how do they know it? Don't they want to know the site will fall below 60fps in near future?

We had a lot of discussions around this earlier and determined that this particular use case is out of scope for FT. See https://github.com/w3c/frame-timing/issues/47#issuecomment-133675435 + my followup.

> observer.observe({ entryTypes: ['render', 'composite'], frameTimingThreshold: 16 });

I don't think that's necessary. We want the UA to control what a "slow" frame is -- e.g. a background tab runs at lower refresh cycle and gets "longer frames", in which case what was previously "slow" now completes in time and shouldn't trigger slow frame events.

**Comment by igrigorik** [comment]
Resolved via #48.
